name: movies_details
version: 1.0.0+1
publish_to: none
description: Movies Details
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  get: 4.6.5
  expandable_text: ^2.3.0
  carousel_slider: ^4.2.1
  flutter_animate: ^4.2.0+1
  flutter_inappwebview: ^5.7.2+3
  youtube_player_flutter: ^8.1.2
  intl: ^0.18.1
  photo_view: ^0.14.0
  connectivity_plus: ^6.0.5

  #fonts and icons
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_iconly: ^1.0.2

  #caching
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.2.3


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_native_splash: ^2.3.1


flutter: 
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  android: true

  background_image: "assets/images/splash-bg.png"
  image: "assets/images/app-logo.png"

  #dart run flutter_native_splash:create