name: movies_details
version: 1.0.0+1
publish_to: none
description: Movies Details
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  get: 4.6.5
  google_fonts: ^5.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

